server:
  ssl:
    key-store: classpath:keystore/${spring.profiles.active}/keystore.jks
    key-store-password: password
    key-password: password
eureka:
  client:
    service-url:
      defaultZone: https://eureka:pass_123@192.168.20.94:8100/eureka/
logging:
  path: ./log
  level:
    com.qy: INFO
    root: INFO
database:
  link:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6e3308v0u0og2eto.mysql.rds.aliyuncs.com:3306/link_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: aere
    password: 123
    type: com.alibaba.druid.pool.xa.DruidXADataSource
  common:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-uf6e3308v0u0og2eto.mysql.rds.aliyuncs.com:3306/common_db?autoReconnect=true&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: qybx_dev
    password: dev@123456
    type: com.alibaba.druid.pool.xa.DruidXADataSource