spring:
  application:
    name: business-client
  profiles:
    active: dev
  cloud:
    inetutils:
      ignored-interfaces:
        - docker0
        - veth.*
server:
  port: 10090
eureka:
  instance:
    prefer-ip-address: true
    leaseRenewalIntervalInSeconds: 10
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka/

